//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.WinForm.Designer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.WinForm.Designer.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnAdd 的本地化字符串。
        /// </summary>
        internal static string btnAddName {
            get {
                return ResourceManager.GetString("btnAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnCancel 的本地化字符串。
        /// </summary>
        internal static string btnCancelName {
            get {
                return ResourceManager.GetString("btnCancelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增子项 的本地化字符串。
        /// </summary>
        internal static string btnChildAdd {
            get {
                return ResourceManager.GetString("btnChildAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnChildAdd 的本地化字符串。
        /// </summary>
        internal static string btnChildAddName {
            get {
                return ResourceManager.GetString("btnChildAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnClose 的本地化字符串。
        /// </summary>
        internal static string btnCloseName {
            get {
                return ResourceManager.GetString("btnCloseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制新增 的本地化字符串。
        /// </summary>
        internal static string btnCopyAdd {
            get {
                return ResourceManager.GetString("btnCopyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnCopyAdd 的本地化字符串。
        /// </summary>
        internal static string btnCopyAddName {
            get {
                return ResourceManager.GetString("btnCopyAddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnDelete 的本地化字符串。
        /// </summary>
        internal static string btnDeleteName {
            get {
                return ResourceManager.GetString("btnDeleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnEdit 的本地化字符串。
        /// </summary>
        internal static string btnEditName {
            get {
                return ResourceManager.GetString("btnEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类(&amp;K) 的本地化字符串。
        /// </summary>
        internal static string btnKind {
            get {
                return ResourceManager.GetString("btnKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnKind 的本地化字符串。
        /// </summary>
        internal static string btnKindName {
            get {
                return ResourceManager.GetString("btnKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnOK 的本地化字符串。
        /// </summary>
        internal static string btnOKName {
            get {
                return ResourceManager.GetString("btnOKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回(&amp;R) 的本地化字符串。
        /// </summary>
        internal static string btnReturn {
            get {
                return ResourceManager.GetString("btnReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnReturn 的本地化字符串。
        /// </summary>
        internal static string btnReturnName {
            get {
                return ResourceManager.GetString("btnReturnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnSave 的本地化字符串。
        /// </summary>
        internal static string btnSaveName {
            get {
                return ResourceManager.GetString("btnSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看(&amp;V) 的本地化字符串。
        /// </summary>
        internal static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 btnView 的本地化字符串。
        /// </summary>
        internal static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确的按钮类型 的本地化字符串。
        /// </summary>
        internal static string ErrorButtonStyle {
            get {
                return ResourceManager.GetString("ErrorButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FengSharp.OneCardAccess.Infrastructure.WinForm.Base.BaseForm,FengSharp.OneCardAccess.Infrastructure.WinForm 的本地化字符串。
        /// </summary>
        internal static string FormTypeString {
            get {
                return ResourceManager.GetString("FormTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FengSharp.OneCardAccess.Infrastructure.WinForm.Base.BaseGridView,FengSharp.OneCardAccess.Infrastructure.WinForm 的本地化字符串。
        /// </summary>
        internal static string GridViewTypeString {
            get {
                return ResourceManager.GetString("GridViewTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FengSharp.OneCardAccess.Infrastructure.WinForm.Base.BaseLayoutControl,FengSharp.OneCardAccess.Infrastructure.WinForm 的本地化字符串。
        /// </summary>
        internal static string LayoutControlTypeString {
            get {
                return ResourceManager.GetString("LayoutControlTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FengSharp.OneCardAccess.Infrastructure.WinForm.Base.BaseSimpleButton,FengSharp.OneCardAccess.Infrastructure.WinForm 的本地化字符串。
        /// </summary>
        internal static string SimpleButtonTypeString {
            get {
                return ResourceManager.GetString("SimpleButtonTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FengSharp.OneCardAccess.Infrastructure.WinForm.Base.BaseTreeList,FengSharp.OneCardAccess.Infrastructure.WinForm 的本地化字符串。
        /// </summary>
        internal static string TreeListTypeString {
            get {
                return ResourceManager.GetString("TreeListTypeString", resourceCulture);
            }
        }
    }
}
