select * from T_DlyNdx
select * from T_PDly
select * from T_PInOutDetails
select * from T_PFBNInOutDetails
select * from T_PSNInOutDetails
select * from T_PInvent
select * from T_PSNInvent
select * from T_PBNInvent
select * from T_PFBNInvent