//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FengSharp.OneCardAccess.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FengSharp.OneCardAccess.Infrastructure.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 创建失败 的本地化字符串。
        /// </summary>
        public static string AddFailure {
            get {
                return ResourceManager.GetString("AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增成功 的本地化字符串。
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象被引用不可删除 的本地化字符串。
        /// </summary>
        public static string BeReferencedCanNotDelete {
            get {
                return ResourceManager.GetString("BeReferencedCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可删除 的本地化字符串。
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类成功 的本地化字符串。
        /// </summary>
        public static string CateSuccess {
            get {
                return ResourceManager.GetString("CateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真的要删除吗？ 的本地化字符串。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除数据失败 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确的类型 的本地化字符串。
        /// </summary>
        public static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        public static string Exception_Title {
            get {
                return ResourceManager.GetString("Exception_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号重复 的本地化字符串。
        /// </summary>
        public static string ExistSameNo {
            get {
                return ResourceManager.GetString("ExistSameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有子节点不可删除 的本地化字符串。
        /// </summary>
        public static string HasSonCanNotDelete {
            get {
                return ResourceManager.GetString("HasSonCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Infomation_Title {
            get {
                return ResourceManager.GetString("Infomation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入数据失败 的本地化字符串。
        /// </summary>
        public static string InsertFailed {
            get {
                return ResourceManager.GetString("InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的票据 的本地化字符串。
        /// </summary>
        public static string InvalidTicket {
            get {
                return ResourceManager.GetString("InvalidTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少选择一项 的本地化字符串。
        /// </summary>
        public static string List_AtLeastOne {
            get {
                return ResourceManager.GetString("List_AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体载入失败 的本地化字符串。
        /// </summary>
        public static string LoadFormFailure {
            get {
                return ResourceManager.GetString("LoadFormFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载数据，请稍后... 的本地化字符串。
        /// </summary>
        public static string LoadingDataPleaseWait {
            get {
                return ResourceManager.GetString("LoadingDataPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载,请稍等...... 的本地化字符串。
        /// </summary>
        public static string LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是末级节点不可选择 的本地化字符串。
        /// </summary>
        public static string NotLastNodeCanSelect {
            get {
                return ResourceManager.GetString("NotLastNodeCanSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象不可为空 的本地化字符串。
        /// </summary>
        public static string ObjCanNotEmpty {
            get {
                return ResourceManager.GetString("ObjCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到对象 的本地化字符串。
        /// </summary>
        public static string ObjectCannotFind {
            get {
                return ResourceManager.GetString("ObjectCannotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string OPFailure {
            get {
                return ResourceManager.GetString("OPFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string OPSuccess {
            get {
                return ResourceManager.GetString("OPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆超时 的本地化字符串。
        /// </summary>
        public static string TimeOutNeedLogin {
            get {
                return ResourceManager.GetString("TimeOutNeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集载入失败 的本地化字符串。
        /// </summary>
        public static string UnityExceptionType_DLLLoadFailure {
            get {
                return ResourceManager.GetString("UnityExceptionType_DLLLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法处理的异常 的本地化字符串。
        /// </summary>
        public static string UnKnowErrorTitle {
            get {
                return ResourceManager.GetString("UnKnowErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新数据失败 的本地化字符串。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在上传,请稍等...... 的本地化字符串。
        /// </summary>
        public static string UpLoadingPleaseWait {
            get {
                return ResourceManager.GetString("UpLoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string WCFExceptionType_AuthenticationException {
            get {
                return ResourceManager.GetString("WCFExceptionType_AuthenticationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接服务器失败或未在服务端找到对应的服务 的本地化字符串。
        /// </summary>
        public static string WCFExceptionType_EndpointNotFoundException {
            get {
                return ResourceManager.GetString("WCFExceptionType_EndpointNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用服务方法失败 的本地化字符串。
        /// </summary>
        public static string WCFExceptionType_FaultException {
            get {
                return ResourceManager.GetString("WCFExceptionType_FaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器内部错误 的本地化字符串。
        /// </summary>
        public static string WCFExceptionType_ProtocolException {
            get {
                return ResourceManager.GetString("WCFExceptionType_ProtocolException", resourceCulture);
            }
        }
    }
}
