--Create PROCEDURE P_UpdateProduct
CREATE PROCEDURE P_UpdateProduct
(
	@ProductId int,
	@ProductNo varchar(50),
	@ProductName varchar(100),
	@ProductName1 varchar(100),
	@Spec varchar(100),
	@Spec1 varchar(100),
	@ProductType smallint,
	@ProductImage varchar(200),
	@Unit varchar(5),
	@Material varchar(10),
	@Code varchar(20),
	@GoodCode varchar(50),
	@CheckCodeOne varchar(10),
	@CheckCodeMany varchar(50),
	@PackQty int,
	@CertType smallint,
	@RegisterId varchar(36),
	@MinStore int,
	@MaxStore int,
	@Cycle numeric(9),
	@DrawingId int,
	@IsRemind bit,
	@QtyMode smallint,
	@preprice1 numeric(9),
	@preprice2 numeric(9),
	@preprice3 numeric(9),
	@preprice4 numeric(9),
	@recprice numeric(9),
	@Remark1 varchar(500),
	@Remark2 varchar(500),
	@Remark3 varchar(500),
	@Remark4 varchar(500),
	@Remark5 varchar(500),
	@Remark6 varchar(500),
	@Remark7 varchar(500),
	@Remark8 varchar(500),
	@ShowNo varchar(50),
	@ShowProductName varchar(100),
	@ShowSpec varchar(100),
	@ShowLOrR varchar(5),
	@ShowPos varchar(50),
	@IsShow bit,
	@IsNew bit,
	@NewRemark varchar(500),
	@LastModifyId varchar(36)
)
AS
declare @errmsg varchar(max)
select 1 from T_Product where ProductNo=@ProductNo and ProductId<>@ProductId and Deleted=0
if(@@ROWCOUNT>0) begin select @errmsg=dbo.F_GetError('',1) RAISERROR(@errmsg,11,1) end--编号重复
update T_Product 
set ProductNo=@ProductNo,
	ProductName=@ProductName,
	ProductName1=@ProductName1,
	Spec=@Spec,
	Spec1=@Spec1,
	ProductType=@ProductType,
	ProductImage=@ProductImage,
	Unit=@Unit,
	Material=@Material,
	Code=@Code,
	GoodCode=@GoodCode,
	CheckCodeOne=@CheckCodeOne,
	CheckCodeMany=@CheckCodeMany,
	PackQty=@PackQty,
	CertType=@CertType,
	RegisterId=@RegisterId,
	MinStore=@MinStore,
	MaxStore=@MaxStore,
	Cycle=@Cycle,
	DrawingId=@DrawingId,
	IsRemind=@IsRemind,
	QtyMode=@QtyMode,
	preprice1=@preprice1,
	preprice2=@preprice2,
	preprice3=@preprice3,
	preprice4=@preprice4,
	recprice=@recprice,
	Remark1=@Remark1,
	Remark2=@Remark2,
	Remark3=@Remark3,
	Remark4=@Remark4,
	Remark5=@Remark5,
	Remark6=@Remark6,
	Remark7=@Remark7,
	Remark8=@Remark8,
	ShowNo=@ShowNo,
	ShowProductName=@ShowProductName,
	ShowSpec=@ShowSpec,
	ShowLOrR=@ShowLOrR,
	ShowPos=@ShowPos,
	IsShow=@IsShow,
	IsNew=@IsNew,
	NewRemark=@NewRemark,
	LastModifyId=@LastModifyId,
	LastModifyDate=getdate()
	where ProductId=@ProductId
if(@@ROWCOUNT<=0) begin select @errmsg=dbo.F_GetError('',3) RAISERROR(@errmsg,11,1) end--更新失败
