CREATE PROCEDURE P_UpdateEmployee
--CREATE PROCEDURE P_UpdateEmployee
(
	@EmpId VARCHAR(36),
	@EmpNo varchar(50),
	@EmpName varchar(50),
	@DeptId varchar(36),
	@Sex varchar(5),
	@Nation varchar(20),
	@Birthday varchar(10),
	@Address varchar(500),
	@TelPhone varchar(20),
	@Mobile varchar(20),
	@Origin varchar(10),
	@Title varchar(50),
	@Duty varchar(50),
	@Post varchar(50),
	@EmpStatus smallint,
	@WedStatus varchar(5),
	@AttCardNo varchar(20),
	@GenCardNo varchar(20),
	@IdCardNo varchar(30),
	@Photo varchar(50),
	@Specialty varchar(50),
	@Diploma varchar(10),
	@GraduateSchool varchar(100),
	@PoliticalStatus varchar(10),
	@JoinDate varchar(10),
	@TrialStartDate varchar(10),
	@TrialEndDate varchar(10),
	@PositiveDate varchar(10),
	@ContractStartDate varchar(10),
	@ContractEndDate varchar(10),
	@HolidaySMS bit,
	@BirthdaySMS bit,
	@Att bit,
	@LastModifyId varchar(36),
	@Remark varchar(200),
	@Remark1 varchar(200),
	@Remark2 varchar(200)
)
AS
declare @errmsg varchar(max)
select 1 from T_Employee where EmpNo=@EmpNo and EmpId<>@EmpId and Deleted=0
if(@@ROWCOUNT>0) begin select @errmsg=dbo.F_GetError('',1) RAISERROR(@errmsg,11,1) end--编号重复
update T_Employee set 
EmpNo=@EmpNo,
EmpName=@EmpName,
DeptId=@DeptId,
Sex=@Sex,
Nation=@Nation,
Birthday=@Birthday,
Address=@Address,
TelPhone=@TelPhone,
Mobile=@Mobile,
Origin=@Origin,
Title=@Title,
Duty=@Duty,
Post=@Post,
EmpStatus=@EmpStatus,
WedStatus=@WedStatus,
AttCardNo=@AttCardNo,
GenCardNo=@GenCardNo,
IdCardNo=@IdCardNo,
Photo=@Photo,
Specialty=@Specialty,
Diploma=@Diploma,
GraduateSchool=@GraduateSchool,
PoliticalStatus=@PoliticalStatus,
JoinDate=@JoinDate,
TrialStartDate=@TrialStartDate,
TrialEndDate=@TrialEndDate,
PositiveDate=@PositiveDate,
ContractStartDate=@ContractStartDate,
ContractEndDate=@ContractEndDate,
HolidaySMS=@HolidaySMS,
BirthdaySMS=@BirthdaySMS,
Att=@Att,
LastModifyId=@LastModifyId,
LastModifyDate=getdate(),
Remark=@Remark,
Remark1=@Remark1,
Remark2=@Remark2
where EmpId=@EmpId

if(@@ROWCOUNT<=0) begin select @errmsg=dbo.F_GetError('',3) RAISERROR(@errmsg,11,1) end--更新失败
